export function mockText(length?: number) {
  return `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Diam maecenas ultricies mi eget mauris pharetra et ultrices. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Arcu vitae elementum curabitur vitae nunc. Turpis massa sed elementum tempus. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Imperdiet sed euismod nisi porta lorem mollis aliquam. Risus pretium quam vulputate dignissim. Pharetra massa massa ultricies mi quis hendrerit dolor. Lacus luctus accumsan tortor posuere ac ut consequat semper viverra. Sapien pellentesque habitant morbi tristique senectus et netus et. Gravida cum sociis natoque penatibus et. A pellentesque sit amet porttitor eget dolor morbi non arcu. Sagittis vitae et leo duis ut.

  Tincidunt vitae semper quis lectus nulla at volutpat. Sit amet aliquam id diam maecenas ultricies mi. Velit egestas dui id ornare arcu odio ut sem nulla. Viverra justo nec ultrices dui sapien eget mi. Malesuada fames ac turpis egestas maecenas. Massa sed elementum tempus egestas. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Convallis aenean et tortor at risus viverra. Sit amet risus nullam eget felis eget nunc. Mauris pharetra et ultrices neque ornare aenean euismod elementum. Praesent tristique magna sit amet purus gravida quis blandit. Massa sed elementum tempus egestas. Eu turpis egestas pretium aenean pharetra magna. Amet risus nullam eget felis. Ornare arcu odio ut sem nulla pharetra diam. Vel pretium lectus quam id. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Eu consequat ac felis donec et odio. Auctor eu augue ut lectus arcu. Felis donec et odio pellentesque diam.
  
  Tristique magna sit amet purus gravida. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Faucibus turpis in eu mi bibendum neque. Nunc id cursus metus aliquam eleifend mi. Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Facilisis volutpat est velit egestas. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Quam nulla porttitor massa id neque aliquam. Est ultricies integer quis auctor elit sed vulputate. Sagittis nisl rhoncus mattis rhoncus. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. Proin sagittis nisl rhoncus mattis rhoncus urna neque viverra justo. Venenatis lectus magna fringilla urna. Ipsum faucibus vitae aliquet nec ullamcorper sit amet. Morbi tristique senectus et netus et.
  
  Magna sit amet purus gravida quis blandit turpis. Donec et odio pellentesque diam volutpat. Nunc sed blandit libero volutpat sed cras ornare arcu. Et malesuada fames ac turpis egestas. Aliquet eget sit amet tellus cras adipiscing enim. Interdum velit euismod in pellentesque massa. Nunc aliquet bibendum enim facilisis gravida. Sit amet justo donec enim diam vulputate ut. Laoreet sit amet cursus sit. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Interdum consectetur libero id faucibus nisl tincidunt eget. Phasellus egestas tellus rutrum tellus. Facilisi nullam vehicula ipsum a. Vitae et leo duis ut diam quam nulla porttitor. Neque convallis a cras semper auctor. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque.
  
  Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Quis vel eros donec ac. Sagittis vitae et leo duis. Pharetra sit amet aliquam id diam maecenas ultricies. Habitant morbi tristique senectus et netus et malesuada fames. Ut ornare lectus sit amet est. Sit amet consectetur adipiscing elit pellentesque habitant. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. In cursus turpis massa tincidunt. Sit amet volutpat consequat mauris nunc congue. Scelerisque eleifend donec pretium vulputate. Orci dapibus ultrices in iaculis nunc sed.`.slice(
    0,
    length
  );
}
